# Generated by Django 3.2.7 on 2022-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('featured', 'featured'), ('unfeatured', 'unfeatured')], default='latest', max_length=20),
        ),
    ]
