# Generated by Django 3.2.7 on 2022-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('featured', 'featured'), ('unfeatured', 'unfeatured')], default='unfeatured', max_length=20),
        ),
    ]
