# Generated by Django 3.2.7 on 2022-01-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_inspiration',
            field=models.BooleanField(default=False),
        ),
    ]
